version: "3.8"

services:
  # redis-ob-ms:
  #   build:
  #     context: scripts/Redis/CVE-2023-45145
  #     dockerfile: Dockerfile.redis_cve_2023_45145
  #   container_name: db-redis-offer-banner
  #   ports:
  #     - 6379:6379
  #   networks:
  #     - vittmitra
  #   volumes:
  #     - ./scripts/Redis/CVE-2023-45145/redis.conf:/etc/redis/redis.conf
  #   command: ["redis-server", "/etc/redis/redis.conf"]

  redis-ob-ms:
    # image: redis:6.0-alpine
    image: redis:6.2.12
    container_name: db-redis-offer-banner
    ports:
      - 6379:6379
    networks:
      - vittmitra
    volumes:
      # - ./src/offer_banner/conf/:/etc/redis/
      - ./scripts/Redis/CVE-2022-24834/conf:/etc/redis/
    command: ["redis-server", "/etc/redis/redis.conf"]

  redis-search-ms:
    image: redis:6.0-alpine
    container_name: db-redis-search
    ports:
      - 6380:6379
    networks:
      - vittmitra
    volumes:
      - ./src/search/conf/:/etc/redis/
    command: ["redis-server", "/etc/redis/redis.conf"]

  mongo:
    image: mongo:7.0
    container_name: db-mongo-bank-info
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongocontact
      - MONGO_INITDB_ROOT_PASSWORD=contact
    ports:
      - 27017:27017
    networks:
      - vittmitra
    volumes:
      # - ./src/contact/conf/:/etc/mongo
      - mongo_data:/data/db

  mongo-express:
    image: mongo-express
    container_name: db-mongo-express
    ports:
      - 8081:8081
    networks:
      - vittmitra
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=mongocontact
      - ME_CONFIG_MONGODB_ADMINPASSWORD=contact
      - ME_CONFIG_MONGODB_SERVER=mongo
    depends_on:
      - mongo

  offer-banner:
    build:
      context: ./src/offer_banner
      dockerfile: Dockerfile.offer_banner
    container_name: ms-offer-banner
    volumes:
      - ./src/offer_banner/app.py:/app/app.py
      - ./src/offer_banner/conf/redis.conf:/app/conf/redis.conf
      - ./src/offer_banner/templates/index.html:/app/templates/index.html
      - ./src/offer_banner/requirements.txt:/app/requirements.txt
    ports:
      - 5002:5002
    networks:
      - vittmitra
    environment:
      - SELF_PORT=5002
      - REDIS_HOST=db-redis-offer-banner
      - REDIS_PORT=6379
      - REDIS_PASSWORD=offer_banner_cve-2022-24834
    command: python app.py
    depends_on:
      - redis-ob-ms
      - mongo

  contacts:
    build:
      context: ./src/contact
      dockerfile: Dockerfile.contact
    container_name: ms-contacts
    volumes:
      - ./src/contact/app.py:/app/app.py
      - ./src/contact/conf/mongo.conf:/app/conf/mongo.conf
      - ./src/contact/templates/index.html:/app/templates/index.html
      - ./src/contact/templates/contact.html:/app/templates/contact.html
      - ./src/contact/requirements.txt:/app/requirements.txt
    ports:
      - 5003:5003
    networks:
      - vittmitra
    environment:
      - SELF_PORT=5003
      - MONGO_DB_HOST=db-mongo-bank-info
      - MONGO_DB_PORT=27017
      - MONGO_DB_USERNAME=mongocontact
      - MONGO_DB_PASSWORD=contact
    command: python app.py
    depends_on:
      - mongo
      - offer-banner

  search:
    build:
      context: ./src/search
      dockerfile: Dockerfile.search
    container_name: ms-search
    volumes:
      - ./src/search/app.py:/app/app.py
      - ./src/search/conf/redis.conf:/app/conf/redis.conf
      - ./src/search/requirements.txt:/app/requirements.txt
      - ./src/search/templates/:/app/templates/
      - ./src/search/static/:/app/static/
    ports:
      - 5004:5004
    networks:
      - vittmitra
    environment:
      - SELF_PORT=5004
      - MONGO_DB_HOST=db-mongo-bank-info
      - MONGO_DB_PORT=27017
      - MONGO_DB_USERNAME=mongocontact
      - MONGO_DB_PASSWORD=contact
      - SEARCH_REDIS_HOST=db-redis-search
      - SEARCH_REDIS_PORT=6380
      - SEARCH_REDIS_PASSWORD=search_complexpass
    command: python app.py
    depends_on:
      - redis-search-ms
      - mongo
      - contacts

  frontend:
    build:
      context: ./src/frontend
      dockerfile: Dockerfile.frontend
    container_name: ms-frontend
    volumes:
      - ./src/frontend/static/:/app/static/
      - ./src/frontend/templates/:/app/templates/
      - ./src/frontend/app.py:/app/app.py
    ports:
      - 5001:5001
    networks:
      - vittmitra
    environment:
      - SELF_PORT=5001
      - OFFER_BANNER_SERVICE_HOST=ms-offer-banner
      - OFFER_BANNER_SERVICE_PORT=5002
      - CONTACT_SERVICE_HOST=ms-contacts
      - CONTACT_SERVICE_PORT=5003
      - SEARCH_SERVICE_HOST=ms-search
      - SEARCH_SERVICE_PORT=5004
    command: python app.py
    depends_on:
      - offer-banner
      - contacts
      - search
      - redis-ob-ms
      - redis-search-ms
      - mongo

volumes:
  mongo_data:
    driver: local

networks:
  vittmitra:
    driver: bridge
